[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=61.2", "setuptools-scm[toml]>=3.4" ]

[project]
name = "django-haystack"
description = "Pluggable search for Django."
readme = "README.rst"
license = "BSD-3-Clause"
license-files = [ "LICENSE" ]
authors = [ { name = "Daniel Lindsley", email = "daniel@toastdriven.com" } ]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.1",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
    "Framework :: Django :: 6.1",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Free Threading",
    "Topic :: Utilities",
]
dynamic = [
    "version",
]
dependencies = [
    "django>=4.2",
    "packaging",
]
optional-dependencies.elasticsearch = [
    "elasticsearch<8,>=5",
]
optional-dependencies.testing = [
    "coverage",
    "geopy==2",
    "pysolr>=3.7",
    "python-dateutil",
    "requests",
    "whoosh<3,>=2.5.4",
]
urls.Documentation = "https://django-haystack.readthedocs.io"
urls.Homepage = "http://haystacksearch.org/"
urls.Source = "https://github.com/django-haystack/django-haystack"

[tool.setuptools]
packages = [
    "haystack",
    "haystack.backends",
    "haystack.management",
    "haystack.management.commands",
    "haystack.templatetags",
    "haystack.utils",
]
include-package-data = false
package-data.haystack = [
    "templates/panels/*",
    "templates/search_configuration/*",
]
zip-safe = false
# test-suite = "test_haystack.run_tests.run_all"  # validate-pyproject-toml will complain

[tool.setuptools_scm]
fallback_version = "0.0.dev0"
write_to = "haystack/version.py"

[tool.ruff]
line-length = 162
extend-exclude = [ "test_haystack/*" ]
lint.select = [ "ASYNC", "B", "C4", "DJ", "E", "F", "G", "PLR091", "W" ]
lint.ignore = [ "B018", "B028", "B904", "B905" ]
lint.isort.known-first-party = [ "haystack", "test_haystack" ]
lint.mccabe.max-complexity = 14
lint.pylint.max-args = 20
lint.pylint.max-branches = 40
lint.pylint.max-returns = 8
lint.pylint.max-statements = 91

[tool.isort]
profile = "black"
multi_line_output = 3
known_first_party = [ "haystack", "test_haystack" ]

[tool.pyproject-fmt]
indent = 4
