name: "PyPI releases"

on: release

jobs:
  build:
    name: Build Python distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Build distributions
        run: pipx run build

      - uses: actions/upload-artifact@v7
        with:
          path: dist/

  pypi-publish:
    name: Upload release to PyPI
    if: github.event_name == 'release' && github.event.action == 'published'
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/django-haystack
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
